export const REQUEST_START = 'REQUEST_START';
export const REQUEST_ERROR = 'REQUEST_ERROR';

export const DISHES_REQUEST_SUCCES = 'DISHES_REQUEST_SUCCES';

export const ADD_DISH_TO_CART = 'ADD_DISH_TO_CART';
export const REMOVE_DISH_FROM_CART = 'REMOVE_DISH_FROM_CART';
export const INIT_CART = 'INIT_CART';

export const ORDER_REQUEST_SUCCES = 'ORDER_REQUEST_SUCCES';
export const ORDER_INIT = 'ORDER_INIT';

export const ORDERS_REQUEST_SUCCES = 'ORDERS_REQUEST_SUCCES';

